#!/system/bin/sh

# IO
BLOCK_DEVS=`ls -d /sys/block/mmc*`;

for i in $BLOCK_DEVS;
do
    echo "0" > $i/queue/rotational;
    echo "256" > $i/queue/max_sectors_kb;
done;

# File System Mounts
#
busybox mount -o remount,noatime,barrier=0,nobh /system
busybox mount -o remount,noatime /data
busybox mount -o remount,noatime,barrier=0,nobh /cache

# maintain caches
busybox rm -f /cache/*.apk
busybox rm -f /cache/*.tmp
busybox rm -f /data/dalvik-cache/*.apk
busybox rm -f /data/dalvik-cache/*.tmp

#VM/FS
sysctl -w fs.lease-break-time=10;
sysctl -w fs.file-max=65536;
sysctl -w vm.overcommit_memory=1;
sysctl -w vm.min_free_order_shift=4;
sysctl -w vm.block_dump=0;
sysctl -w vm.oom_dump_tasks=1;
sysctl -w vm.page-cluster=3;

