# Nmap
PRODUCT_COPY_FILES +=  \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/bin/ncat:data/data/jackpal.androidterm/nmap/bin/ncat \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/bin/ndiff:data/data/jackpal.androidterm/nmap/bin/ndiff \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/bin/nmap:data/data/jackpal.androidterm/nmap/bin/nmap \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/bin/nping:data/data/jackpal.androidterm/nmap/bin/nping \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/ncat/ca-bundle.crt:data/data/jackpal.androidterm/nmap/share/ncat/ca-bundle.crt \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/nmap-mac-prefixes:data/data/jackpal.androidterm/nmap/share/nmap/nmap-mac-prefixes \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/nmap-os-db:data/data/jackpal.androidterm/nmap/share/nmap/nmap-os-db \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/nmap-payloads:data/data/jackpal.androidterm/nmap/share/nmap/nmap-payloads \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/nmap-protocols:data/data/jackpal.androidterm/nmap/share/nmap/nmap-protocols \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/nmap-rpc:data/data/jackpal.androidterm/nmap/share/nmap/nmap-rpc \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/nmap-service-probes:data/data/jackpal.androidterm/nmap/share/nmap/nmap-service-probes \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/nmap-services:data/data/jackpal.androidterm/nmap/share/nmap/nmap-services \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/nmap.dtd:data/data/jackpal.androidterm/nmap/share/nmap/nmap.dtd \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/nmap.xsl:data/data/jackpal.androidterm/nmap/share/nmap/nmap.xsl \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/nse_main.lua:data/data/jackpal.androidterm/nmap/share/nmap/nse_main.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/afp.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/afp.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/amqp.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/amqp.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/asn1.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/asn1.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/base64.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/base64.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/bitcoin.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/bitcoin.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/bittorrent.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/bittorrent.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/brute.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/brute.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/citrixxml.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/citrixxml.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/comm.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/comm.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/creds.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/creds.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/cvs.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/cvs.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/datafiles.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/datafiles.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/dhcp.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/dhcp.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/dns.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/dns.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/dnsbl.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/dnsbl.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/dnssd.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/dnssd.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/drda.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/drda.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ftp.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/ftp.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/giop.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/giop.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/http.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/httpspider.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/httpspider.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/imap.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/imap.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/informix.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/informix.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ipOps.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/ipOps.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/iscsi.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/iscsi.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/json.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/json.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ldap.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/ldap.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/listop.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/listop.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/match.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/match.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/mongodb.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/mongodb.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/msrpc.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/msrpc.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/msrpcperformance.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/msrpcperformance.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/msrpctypes.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/msrpctypes.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/mssql.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/mssql.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/mysql.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/mysql.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ncp.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/ncp.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/netbios.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/netbios.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/nrpc.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/nrpc.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/nsedebug.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/nsedebug.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/omp2.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/omp2.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/packet.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/packet.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/pgsql.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/pgsql.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/pop3.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/pop3.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/proxy.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/proxy.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/rmi.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/rmi.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/rpc.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/rpc.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/rtsp.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/rtsp.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/sasl.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/sasl.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/shortport.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/shortport.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/sip.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/sip.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/smb.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/smb.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/smbauth.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/smbauth.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/smtp.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/smtp.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/snmp.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/snmp.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/srvloc.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/srvloc.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ssh1.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/ssh1.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ssh2.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/ssh2.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/stdnse.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/stdnse.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/strbuf.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/strbuf.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/strict.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/strict.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/tab.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/tab.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/target.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/target.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/tftp.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/tftp.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/tns.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/tns.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/unpwdb.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/unpwdb.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/upnp.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/upnp.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/url.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/url.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/vnc.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/vnc.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/vulns.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/vulns.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/vuzedht.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/vuzedht.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/wsdd.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/wsdd.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/xmpp.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/xmpp.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/favicon-db:data/data/jackpal.androidterm/nmap/share/nmap/nselib/data/favicon-db \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-default-accounts-fingerprints.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/data/http-default-accounts-fingerprints.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-fingerprints.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/data/http-fingerprints.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-folders.txt:data/data/jackpal.androidterm/nmap/share/nmap/nselib/data/http-folders.txt \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/mysql-cis.audit:data/data/jackpal.androidterm/nmap/share/nmap/nselib/data/mysql-cis.audit \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/oracle-default-accounts.lst:data/data/jackpal.androidterm/nmap/share/nmap/nselib/data/oracle-default-accounts.lst \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/oracle-sids:data/data/jackpal.androidterm/nmap/share/nmap/nselib/data/oracle-sids \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/packetdecoders.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/data/packetdecoders.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/passwords.lst:data/data/jackpal.androidterm/nmap/share/nmap/nselib/data/passwords.lst \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/rtsp-urls.txt:data/data/jackpal.androidterm/nmap/share/nmap/nselib/data/rtsp-urls.txt \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/snmpcommunities.lst:data/data/jackpal.androidterm/nmap/share/nmap/nselib/data/snmpcommunities.lst \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ssl-ciphers:data/data/jackpal.androidterm/nmap/share/nmap/nselib/data/ssl-ciphers \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ssl-fingerprints:data/data/jackpal.androidterm/nmap/share/nmap/nselib/data/ssl-fingerprints \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/tftplist.txt:data/data/jackpal.androidterm/nmap/share/nmap/nselib/data/tftplist.txt \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/usernames.lst:data/data/jackpal.androidterm/nmap/share/nmap/nselib/data/usernames.lst \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/wp-plugins.lst:data/data/jackpal.androidterm/nmap/share/nmap/nselib/data/wp-plugins.lst \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/README:data/data/jackpal.androidterm/nmap/share/nmap/nselib/data/psexec/README \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/backdoor.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/data/psexec/backdoor.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/default.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/data/psexec/default.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/drives.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/data/psexec/drives.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/examples.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/data/psexec/examples.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/experimental.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/data/psexec/experimental.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/network.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/data/psexec/network.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/nmap_service.c:data/data/jackpal.androidterm/nmap/share/nmap/nselib/data/psexec/nmap_service.c \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/nmap_service.vcproj:data/data/jackpal.androidterm/nmap/share/nmap/nselib/data/psexec/nmap_service.vcproj \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/pwdump.lua:data/data/jackpal.androidterm/nmap/share/nmap/nselib/data/psexec/pwdump.lua \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/address-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/address-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/afp-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/afp-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/afp-ls.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/afp-ls.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/afp-path-vuln.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/afp-path-vuln.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/afp-serverinfo.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/afp-serverinfo.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/afp-showmount.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/afp-showmount.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/amqp-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/amqp-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/asn-query.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/asn-query.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/auth-owners.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/auth-owners.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/auth-spoof.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/auth-spoof.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/backorifice-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/backorifice-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/backorifice-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/backorifice-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/banner.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/banner.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/bitcoin-getaddr.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/bitcoin-getaddr.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/bitcoin-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/bitcoin-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/bitcoinrpc-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/bitcoinrpc-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/bittorrent-discovery.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/bittorrent-discovery.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/broadcast-avahi-dos.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/broadcast-avahi-dos.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/broadcast-db2-discover.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/broadcast-db2-discover.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/broadcast-dhcp-discover.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/broadcast-dhcp-discover.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/broadcast-dns-service-discovery.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/broadcast-dns-service-discovery.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/broadcast-dropbox-listener.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/broadcast-dropbox-listener.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/broadcast-listener.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/broadcast-listener.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/broadcast-ms-sql-discover.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/broadcast-ms-sql-discover.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/broadcast-netbios-master-browser.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/broadcast-netbios-master-browser.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/broadcast-novell-locate.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/broadcast-novell-locate.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/broadcast-pc-anywhere.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/broadcast-pc-anywhere.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/broadcast-pc-duo.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/broadcast-pc-duo.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/broadcast-ping.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/broadcast-ping.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/broadcast-rip-discover.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/broadcast-rip-discover.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/broadcast-sybase-asa-discover.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/broadcast-sybase-asa-discover.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/broadcast-upnp-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/broadcast-upnp-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/broadcast-wake-on-lan.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/broadcast-wake-on-lan.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/broadcast-wpad-discover.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/broadcast-wpad-discover.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/broadcast-wsdd-discover.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/broadcast-wsdd-discover.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/citrix-brute-xml.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/citrix-brute-xml.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/citrix-enum-apps-xml.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/citrix-enum-apps-xml.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/citrix-enum-apps.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/citrix-enum-apps.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/citrix-enum-servers-xml.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/citrix-enum-servers-xml.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/citrix-enum-servers.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/citrix-enum-servers.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/couchdb-databases.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/couchdb-databases.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/couchdb-stats.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/couchdb-stats.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/creds-summary.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/creds-summary.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/cvs-brute-repository.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/cvs-brute-repository.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/cvs-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/cvs-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/daap-get-library.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/daap-get-library.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/daytime.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/daytime.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/db2-das-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/db2-das-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/db2-discover.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/db2-discover.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/dhcp-discover.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/dhcp-discover.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/dns-blacklist.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/dns-blacklist.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/dns-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/dns-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/dns-cache-snoop.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/dns-cache-snoop.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/dns-fuzz.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/dns-fuzz.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/dns-nsec-enum.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/dns-nsec-enum.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/dns-random-srcport.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/dns-random-srcport.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/dns-random-txid.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/dns-random-txid.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/dns-recursion.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/dns-recursion.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/dns-service-discovery.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/dns-service-discovery.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/dns-update.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/dns-update.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/dns-zeustracker.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/dns-zeustracker.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/dns-zone-transfer.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/dns-zone-transfer.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/domcon-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/domcon-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/domcon-cmd.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/domcon-cmd.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/domino-enum-users.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/domino-enum-users.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/dpap-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/dpap-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/drda-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/drda-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/drda-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/drda-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/epmd-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/epmd-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/finger.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/finger.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/firewalk.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/firewalk.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ftp-anon.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ftp-anon.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ftp-bounce.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ftp-bounce.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ftp-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ftp-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ftp-libopie.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ftp-libopie.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ftp-proftpd-backdoor.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ftp-proftpd-backdoor.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ftp-vsftpd-backdoor.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ftp-vsftpd-backdoor.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ftp-vuln-cve2010-4221.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ftp-vuln-cve2010-4221.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ganglia-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ganglia-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/giop-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/giop-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/gopher-ls.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/gopher-ls.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/hadoop-datanode-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/hadoop-datanode-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/hadoop-jobtracker-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/hadoop-jobtracker-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/hadoop-namenode-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/hadoop-namenode-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/hadoop-secondary-namenode-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/hadoop-secondary-namenode-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/hadoop-tasktracker-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/hadoop-tasktracker-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/hbase-master-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/hbase-master-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/hbase-region-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/hbase-region-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/hddtemp-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/hddtemp-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/hostmap.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/hostmap.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-affiliate-id.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-affiliate-id.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-apache-negotiation.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-apache-negotiation.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-auth.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-auth.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-awstatstotals-exec.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-awstatstotals-exec.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-axis2-dir-traversal.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-axis2-dir-traversal.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-backup-finder.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-backup-finder.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-barracuda-dir-traversal.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-barracuda-dir-traversal.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-cakephp-version.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-cakephp-version.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-cors.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-cors.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-date.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-date.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-default-accounts.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-default-accounts.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-domino-enum-passwords.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-domino-enum-passwords.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-email-harvest.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-email-harvest.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-enum.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-enum.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-favicon.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-favicon.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-form-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-form-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-google-malware.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-google-malware.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-grep.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-grep.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-headers.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-headers.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-iis-webdav-vuln.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-iis-webdav-vuln.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-joomla-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-joomla-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-litespeed-sourcecode-download.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-litespeed-sourcecode-download.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-majordomo2-dir-traversal.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-majordomo2-dir-traversal.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-malware-host.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-malware-host.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-method-tamper.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-method-tamper.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-methods.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-methods.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-open-proxy.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-open-proxy.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-open-redirect.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-open-redirect.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-passwd.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-passwd.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-php-version.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-php-version.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-put.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-put.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-robots.txt.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-robots.txt.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-robtex-reverse-ip.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-robtex-reverse-ip.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-title.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-title.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-trace.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-trace.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-unsafe-output-escaping.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-unsafe-output-escaping.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-userdir-enum.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-userdir-enum.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-vhosts.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-vhosts.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-vmware-path-vuln.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-vmware-path-vuln.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-vuln-cve2011-3192.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-vuln-cve2011-3192.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-vuln-cve2011-3368.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-vuln-cve2011-3368.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-waf-detect.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-waf-detect.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-wordpress-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-wordpress-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-wordpress-enum.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-wordpress-enum.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/http-wordpress-plugins.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/http-wordpress-plugins.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/iax2-version.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/iax2-version.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/imap-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/imap-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/imap-capabilities.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/imap-capabilities.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/informix-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/informix-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/informix-query.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/informix-query.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/informix-tables.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/informix-tables.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ip-geolocation-geobytes.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ip-geolocation-geobytes.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ip-geolocation-geoplugin.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ip-geolocation-geoplugin.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ip-geolocation-ipinfodb.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ip-geolocation-ipinfodb.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ip-geolocation-maxmind.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ip-geolocation-maxmind.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ipidseq.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ipidseq.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ipv6-node-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ipv6-node-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/irc-botnet-channels.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/irc-botnet-channels.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/irc-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/irc-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/irc-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/irc-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/irc-unrealircd-backdoor.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/irc-unrealircd-backdoor.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/iscsi-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/iscsi-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/iscsi-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/iscsi-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/jdwp-version.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/jdwp-version.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/krb5-enum-users.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/krb5-enum-users.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ldap-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ldap-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ldap-novell-getpass.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ldap-novell-getpass.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ldap-rootdse.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ldap-rootdse.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ldap-search.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ldap-search.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/lexmark-config.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/lexmark-config.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/lltd-discovery.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/lltd-discovery.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/maxdb-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/maxdb-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/metasploit-xmlrpc-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/metasploit-xmlrpc-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/modbus-discover.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/modbus-discover.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/mongodb-databases.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/mongodb-databases.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/mongodb-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/mongodb-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ms-sql-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ms-sql-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ms-sql-config.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ms-sql-config.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ms-sql-dump-hashes.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ms-sql-dump-hashes.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ms-sql-empty-password.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ms-sql-empty-password.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ms-sql-hasdbaccess.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ms-sql-hasdbaccess.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ms-sql-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ms-sql-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ms-sql-query.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ms-sql-query.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ms-sql-tables.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ms-sql-tables.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ms-sql-xp-cmdshell.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ms-sql-xp-cmdshell.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/mysql-audit.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/mysql-audit.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/mysql-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/mysql-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/mysql-databases.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/mysql-databases.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/mysql-empty-password.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/mysql-empty-password.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/mysql-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/mysql-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/mysql-users.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/mysql-users.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/mysql-variables.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/mysql-variables.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/nat-pmp-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/nat-pmp-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/nbstat.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/nbstat.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ncp-enum-users.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ncp-enum-users.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ncp-serverinfo.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ncp-serverinfo.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/nessus-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/nessus-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/netbus-auth-bypass.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/netbus-auth-bypass.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/netbus-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/netbus-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/netbus-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/netbus-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/netbus-version.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/netbus-version.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/nexpose-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/nexpose-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/nfs-ls.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/nfs-ls.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/nfs-showmount.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/nfs-showmount.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/nfs-statfs.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/nfs-statfs.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/nping-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/nping-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/nrpe-enum.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/nrpe-enum.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ntp-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ntp-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ntp-monlist.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ntp-monlist.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/omp2-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/omp2-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/omp2-enum-targets.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/omp2-enum-targets.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/openlookup-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/openlookup-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/openvas-otp-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/openvas-otp-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/oracle-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/oracle-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/oracle-enum-users.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/oracle-enum-users.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/oracle-sid-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/oracle-sid-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ovs-agent-version.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ovs-agent-version.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/p2p-conficker.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/p2p-conficker.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/path-mtu.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/path-mtu.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/pgsql-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/pgsql-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/pjl-ready-message.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/pjl-ready-message.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/pop3-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/pop3-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/pop3-capabilities.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/pop3-capabilities.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/pptp-version.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/pptp-version.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/qscan.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/qscan.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/quake3-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/quake3-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/quake3-master-getservers.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/quake3-master-getservers.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/realvnc-auth-bypass.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/realvnc-auth-bypass.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/resolveall.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/resolveall.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/reverse-index.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/reverse-index.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/rexec-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/rexec-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/rlogin-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/rlogin-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/rmi-dumpregistry.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/rmi-dumpregistry.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/rpcinfo.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/rpcinfo.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/rtsp-methods.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/rtsp-methods.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/rtsp-url-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/rtsp-url-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/script.db:data/data/jackpal.androidterm/nmap/share/nmap/scripts/script.db \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/servicetags.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/servicetags.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/sip-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/sip-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/sip-enum-users.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/sip-enum-users.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/skypev2-version.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/skypev2-version.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/smb-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/smb-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/smb-check-vulns.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/smb-check-vulns.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/smb-enum-domains.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/smb-enum-domains.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/smb-enum-groups.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/smb-enum-groups.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/smb-enum-processes.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/smb-enum-processes.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/smb-enum-sessions.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/smb-enum-sessions.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/smb-enum-shares.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/smb-enum-shares.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/smb-enum-users.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/smb-enum-users.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/smb-flood.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/smb-flood.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/smb-mbenum.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/smb-mbenum.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/smb-os-discovery.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/smb-os-discovery.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/smb-psexec.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/smb-psexec.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/smb-security-mode.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/smb-security-mode.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/smb-server-stats.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/smb-server-stats.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/smb-system-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/smb-system-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/smbv2-enabled.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/smbv2-enabled.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/smtp-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/smtp-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/smtp-commands.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/smtp-commands.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/smtp-enum-users.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/smtp-enum-users.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/smtp-open-relay.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/smtp-open-relay.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/smtp-strangeport.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/smtp-strangeport.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/smtp-vuln-cve2010-4344.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/smtp-vuln-cve2010-4344.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/smtp-vuln-cve2011-1720.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/smtp-vuln-cve2011-1720.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/smtp-vuln-cve2011-1764.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/smtp-vuln-cve2011-1764.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/sniffer-detect.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/sniffer-detect.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/snmp-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/snmp-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/snmp-interfaces.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/snmp-interfaces.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/snmp-ios-config.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/snmp-ios-config.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/snmp-netstat.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/snmp-netstat.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/snmp-processes.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/snmp-processes.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/snmp-sysdescr.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/snmp-sysdescr.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/snmp-win32-services.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/snmp-win32-services.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/snmp-win32-shares.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/snmp-win32-shares.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/snmp-win32-software.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/snmp-win32-software.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/snmp-win32-users.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/snmp-win32-users.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/socks-open-proxy.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/socks-open-proxy.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/sql-injection.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/sql-injection.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ssh-hostkey.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ssh-hostkey.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ssh2-enum-algos.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ssh2-enum-algos.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/sshv1.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/sshv1.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ssl-cert.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ssl-cert.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ssl-enum-ciphers.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ssl-enum-ciphers.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ssl-google-cert-catalog.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ssl-google-cert-catalog.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ssl-known-key.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/ssl-known-key.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/sslv2.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/sslv2.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/stuxnet-detect.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/stuxnet-detect.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/svn-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/svn-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/targets-ipv6-multicast-echo.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/targets-ipv6-multicast-echo.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/targets-ipv6-multicast-invalid-dst.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/targets-ipv6-multicast-invalid-dst.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/targets-ipv6-multicast-slaac.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/targets-ipv6-multicast-slaac.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/targets-sniffer.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/targets-sniffer.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/targets-traceroute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/targets-traceroute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/telnet-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/telnet-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/telnet-encryption.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/telnet-encryption.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/tftp-enum.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/tftp-enum.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/unusual-port.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/unusual-port.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/upnp-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/upnp-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/vnc-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/vnc-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/vnc-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/vnc-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/vuze-dht-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/vuze-dht-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/wdb-version.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/wdb-version.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/whois.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/whois.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/wsdd-discover.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/wsdd-discover.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/x11-access.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/x11-access.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/xmpp-brute.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/xmpp-brute.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/xmpp-info.nse:data/data/jackpal.androidterm/nmap/share/nmap/scripts/xmpp-info.nse \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ncat.1:data/data/jackpal.androidterm/nmap/share/man/man1/ncat.1 \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/ndiff.1:data/data/jackpal.androidterm/nmap/share/man/man1/ndiff.1 \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/nmap.1:data/data/jackpal.androidterm/nmap/share/man/man1/nmap.1 \
	vendor/raumzero/prebuilt/common/data/data/jackpal.androidterm/nmap/share/nmap/nping.1:data/data/jackpal.androidterm/nmap/share/man/man1/nping.1

